### PR TITLE
automated travis config update

### PR DESCRIPTION
**Pull request by missinglink**

### CODE REVIEW

**Comment by trescube** [comment]
:shipit:

**Comment by missinglink** [comment]
passes on nodejs 0.12,4,5,6

**Comment by orangejulius** [comment]
LGTM

One thing all these are missing compared to the OA travis file is a line [installing NPM 2](https://github.com/pelias/openaddresses/blob/master/.travis.yml#L27-L28). This came from a travis file semantic-release generated for me. I'm not sure if it does anything important, so if we see anything weird with all these PRs, it could be because of that.

**Comment by orangejulius** [comment]
Posthumous LGTM

**Pull request merged**
